// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBif9bawXXTcB_iyD55xax8Fqi7-b275Qk',
    appId: '1:257997339909:web:1e51e9a24f1a222faa4b6c',
    messagingSenderId: '257997339909',
    projectId: 'holysong-by-flutter',
    authDomain: 'holysong-by-flutter.firebaseapp.com',
    storageBucket: 'holysong-by-flutter.firebasestorage.app',
    measurementId: 'G-V61FCWF5B6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAJsgw1mtDvQHniqiUFqeHiRYT0ye58C8',
    appId: '1:257997339909:android:c1ce44ae4e236ed1aa4b6c',
    messagingSenderId: '257997339909',
    projectId: 'holysong-by-flutter',
    storageBucket: 'holysong-by-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqoFydJaJFUTr8yLHWLk19pvj2gtb0wPA',
    appId: '1:257997339909:ios:93234b1e8436ee44aa4b6c',
    messagingSenderId: '257997339909',
    projectId: 'holysong-by-flutter',
    storageBucket: 'holysong-by-flutter.firebasestorage.app',
    iosBundleId: 'com.holysong.holysongWeeklyV2',
  );
}